redmine:
  redmine_url: http://redmine.org
  username: username
  password: password

  project_name: redmine-bot

telegram:
  api_token: 1
  chat_white_list:
    - 1
    - 2
  chat_white_list_password: '12345'
