redmine:
  redmine_url: http://redmine.org
  username: username
  password: password

  project_name: redmine-bot

  status_resolved_id: 3 # Resolved решена
  status_in_progress_id: 2 # In progress в работе

telegram:
  api_token: 1
  chat_white_list_password: '12345'
