redmine:
  redmine_url: http://redmine.republic-shkit.org/
  username: feuillemorte
  password: avt45959Root

  project_name: redmine-bot

telegram:
  api_token: 345483005:AAHYUK6QhDgC5v-clrnOZzzN9CGuI0NJq4A
