common:
  # LOG LEVEL:
  # CRITICAL  50
  # ERROR     40
  # WARNING   30
  # INFO      20
  # DEBUG     10
  # NOTSET    0
  log_level: 10

redmine:
  redmine_url: http://redmine.org
  username: username
  password: password

  project_name: redmine-bot

  status_resolved_id: 3 # Resolved решена
  status_in_progress_id: 2 # In progress в работе

  user_ids:
    - 1
    - 2

  updated_time: 300 # seconds
  job_time: 300.0 # seconds

  working_time:
    - 10  # start time
    - 20  # end time

telegram:
  api_token: 1
  chat_white_list_password: '12345'
  bot_name: '@bot_name'
